### ISSUE TITLE
From Zver

### ISSUE THREAD

**Issue by Stinger83** [Drogalchuk/Mud#19]
Коли случайно зайшов в воїд - вибило з ігри

2017-06-05 20:14:36,010 ERROR com.mud.server.GameThread - java.lang.NullPointerException
java.lang.NullPointerException
        at com.mud.model.tables_h.MercDefH.IS_OUTSIDE(MercDefH.java:1772)
        at com.mud.core.update.WeatherUpdate.weather_update(WeatherUpdate.java:146)
        at com.mud.core.update.UpdateC.update_handler(UpdateC.java:415)
        at com.mud.server.GameThread.run(GameThread.java:41)
        at java.lang.Thread.run(Thread.java:748)

**Comment by annadrogalchuk** [comment]
Что значит зайти с воид? Проблема в том, что in_room null. Это непорядок
