### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by Stinger83** [Drogalchuk/Mud#20]
^MTo select codepage type "cp"
^MPress <Enter> to login

2017-06-06 08:32:44,243  INFO com.mud.model.descriptor.TelnetDescriptorData - new>
2017-06-06 08:32:44,243  INFO com.mud.model.descriptor.DescriptorData - new<
^M<C2><E2><E5><E4><E8> <F1><E2><EE><E5> <E8><EC><FF>, <F1><F2><F0><E0><ED><ED><E8><EA>:
2017-06-06 08:32:57,753  INFO com.mud.model.descriptor.TelnetDescriptorData - new>Oldman
2017-06-06 08:32:58,003  INFO com.mud.model.descriptor.TelnetDescriptorData - new>
2017-06-06 08:32:58,013 ERROR com.mud.model.merc_h.MercH - Load_char_obj: # not found.: 0
java.lang.RuntimeException: Load_char_obj: # not found.: 0
        at com.mud.model.merc_h.MercH.bug(MercH.java:131)
        at com.mud.core.db.flatfile.CharDataFlatFileReader.loadCharData(CharDataFlatFileReader.java:89)
        at com.mud.core.save.LoadCharObj.loadCharData(LoadCharObj.java:44)
        at com.mud.server.nanny.PickName.getName(PickName.java:45)
        at com.mud.server.nanny.Nanny.nanny(Nanny.java:53)
        at com.mud.server.GameThread.processInput(GameThread.java:124)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)

2017-06-06 17:15:08,792  INFO com.mud.core.actionWiznet.ActWizC - Stinger:W:offline zveroboy i
2017-06-06 17:15:08,800 ERROR com.mud.model.merc_h.MercH - Load_char_obj: # not found.: 0
java.lang.RuntimeException: Load_char_obj: # not found.: 0
        at com.mud.model.merc_h.MercH.bug(MercH.java:131)
        at com.mud.core.db.flatfile.CharDataFlatFileReader.loadCharData(CharDataFlatFileReader.java:89)
        at com.mud.core.save.LoadCharObj.loadCharData(LoadCharObj.java:44)
        at com.mud.functions.do_fun.DoOffline.execute(DoOffline.java:78)
        at com.mud.core.interp.InterpC.interpret(InterpC.java:298)
        at com.mud.core.interp.InterpC.substitute_alias(InterpC.java:441)
        at com.mud.server.GameThread.processInput(GameThread.java:120)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)
2017-06-06 17:15:08,805 ERROR com.mud.server.GameThread - java.lang.ArrayIndexOutOfBoundsException: 16
java.lang.ArrayIndexOutOfBoundsException: 16
        at com.mud.core.actionInfo.WhoisInfo.classname(WhoisInfo.java:137)
        at com.mud.core.actionInfo.WhoisInfo.whois_info(WhoisInfo.java:25)
        at com.mud.functions.do_fun.DoOffline.execute(DoOffline.java:103)
        at com.mud.core.interp.InterpC.interpret(InterpC.java:298)
        at com.mud.core.interp.InterpC.substitute_alias(InterpC.java:441)
        at com.mud.server.GameThread.processInput(GameThread.java:120)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)

2017-06-06 17:15:40,314  INFO com.mud.model.descriptor.TelnetDescriptorData - Stinger>offline fdfds i

2017-06-06 17:15:40,314  INFO com.mud.core.actionWiznet.ActWizC - Stinger:W:offline fdfds i
2017-06-06 17:15:40,320 ERROR com.mud.server.GameThread - java.lang.ArrayIndexOutOfBoundsException: 16
java.lang.ArrayIndexOutOfBoundsException: 16
        at com.mud.core.actionInfo.WhoisInfo.classname(WhoisInfo.java:137)
        at com.mud.core.actionInfo.WhoisInfo.whois_info(WhoisInfo.java:25)
        at com.mud.functions.do_fun.DoOffline.execute(DoOffline.java:103)
        at com.mud.core.interp.InterpC.interpret(InterpC.java:298)
        at com.mud.core.interp.InterpC.substitute_alias(InterpC.java:441)
        at com.mud.server.GameThread.processInput(GameThread.java:120)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)
2017-06-06 17:15:40,321  INFO com.mud.model.descripto
2017-06-06 18:46:05,292  WARN com.mud.model.descriptor.DescriptorData - java.net.SocketException: Broken pipe (Write failed)
2017-06-06 18:46:17,291  INFO com.mud.core.actionWiznet.ActWizC - <D1><E2><FF><F9><E5><ED><ED><E0><FF>_<D0><EE><F9><E0> has just been reset.
2017-06-06 18:46:17,291  INFO com.mud.core.actionWiznet.ActWizC - <C2><FB><F1><F8><E0><FF>_<C1><E0><F8><ED><FF>_<C2><EE><EB><F8><E5><E1><F1><F2><E2><E0> has just been reset.
2017-06-06 18:46:17,292  INFO com.mud.core.actionWiznet.ActWizC - <D8><EA><EE><EB><E0> has just been reset.
2017-06-06 18:46:17,292  INFO com.mud.core.actionWiznet.ActWizC - <C7><E5><F0><EA><E0><EB><FC><ED><E0><FF>_<D0><E5><E0><EB><FC><ED><EE><F1><F2><FC> has just been reset.
2017-06-06 18:46:17,364  INFO com.mud.model.descriptor.DescriptorData - Stinger<
^M%%%%%%%%%%%!!!!!!!!!!!!!!!!%%%%%%%%%%%%%%%%%%%%%%ESC[0m
^M ESC[0m
^MESC[0mESC[1;37m[ESC[1;35m<D3> <D5><F0><E0><EC><EE><E2><EE><E3><EE> <C0><EB><F2><E0><F0><DF>ESC[1;37m] ESC[0;33mqESC[1;36m7656ESC[0;33mp ESC[0;35m<D3><F2><F0><EE> ESC[1;32mnone
^MESC[1;36m34655/ESC[0;36m34655ESC[0;32mhp ESC[1;36m34435/ESC[0;36m34435ESC[0;32mm ESC[1;36m6305/ESC[0;36m6305ESC[0;32mmv ESC[1;33m4230.ESC[0;37m1564 ESC[1;32mESC[1;32mNESC[0mESC[1;32mSESC[0mESC[1;32mWESC[0mESC[1;32mUESC[0m ESC[1;36m-972
 ESC[1;33m*ESC[1;31m0ESC[1;33m* ESC[1;32m+0 ESC[1;34m3000xpESC[0m
^M ESC[0m
2017-06-06 18:46:17,364  WARN com.mud.model.descriptor.DescriptorData - java.net.SocketException: Broken pipe (Write failed)
2017-06-06 18:47:17,360  INFO com.mud.model.descriptor.DescriptorData - Stinger<
^M%%%%%%%%%%%!!!!!!!!!!!!!!!!%%%%%%%%%%%%%%%%%%%%%%ESC[0m
^M ESC[0m
^MESC[0mESC[1;37m[ESC[1;35m<D3> <D5><F0><E0><EC><EE><E2><EE><E3><EE> <C0><EB><F2><E0><F0><DF>ESC[1;37m] ESC[0;33mqESC[1;36m7656ESC[0;33mp ESC[0;35m<C4><E5><ED><FC> ESC[1;32mnone
^MESC[1;36m34655/ESC[0;36m34655ESC[0;32mhp ESC[1;36m34435/ESC[0;36m34435ESC[0;32mm ESC[1;36m6305/ESC[0;36m6305ESC[0;32mmv ESC[1;33m4230.ESC[0;37m1564 ESC[1;32mESC[1;32mNESC[0mESC[1;32mSESC[0mESC[1;32mWESC[0mESC[1;32mUESC[0m ESC[1;36m-972
 ESC[1;33m*ESC[1;31m0ESC[1;33m* ESC[1;32m+0 ESC[1;34m3000xpESC[0m
^M ESC[0m
2017-06-06 18:47:17,360  WARN com.mud.model.descriptor.DescriptorData - java.net.SocketException: Broken pipe (Write failed)
2017-06-06 18:48:17,359  INFO com.mud.core.actionWiznet.ActWizC - <C2>_<ED><E5><E1><E5>_(In_the_Air) has just been reset.
2017-06-06 18:48:17,360  INFO com.mud.core.actionWiznet.ActWizC - <D4><E0><E1><F0><E8><EA><E0>_<CC><EE><E1><EE><E2> has just been reset.
2017-06-06 18:48:17,360  INFO com.mud.core.actionWiznet.ActWizC - <CD><E8><F0><E2><E0><ED><E0>_(Nirvana) has just been reset.
2017-06-06 18:48:17,360  INFO com.mud.core.actionWiznet.ActWizC - <D8><EA><EE><EB><E0> has just been reset.

2017-06-06 20:11:26,679  INFO com.mud.model.descriptor.TelnetDescriptorData - new>iov

2017-06-06 20:11:26,684 ERROR com.mud.model.merc_h.MercH - Load_char_obj: # not found.: 0
java.lang.RuntimeException: Load_char_obj: # not found.: 0
        at com.mud.model.merc_h.MercH.bug(MercH.java:131)
        at com.mud.core.db.flatfile.CharDataFlatFileReader.loadCharData(CharDataFlatFileReader.java:89)
        at com.mud.core.save.LoadCharObj.loadCharData(LoadCharObj.java:44)
        at com.mud.server.nanny.PickName.getName(PickName.java:45)
        at com.mud.server.nanny.Nanny.nanny(Nanny.java:53)
        at com.mud.server.GameThread.processInput(GameThread.java:124)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)

2017-06-06 20:51:42,134  INFO com.mud.core.actionWiznet.ActWizC - Stinger:W:stat char io
2017-06-06 20:51:42,138 ERROR com.mud.server.GameThread - java.lang.NullPointerException
java.lang.NullPointerException
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
        at java.util.regex.Matcher.reset(Matcher.java:309)
        at java.util.regex.Matcher.<init>(Matcher.java:229)
        at java.util.regex.Pattern.matcher(Pattern.java:1093)
        at com.mud.utils.color.ColorsProcessor.countColorSpecialSigns(ColorsProcessor.java:13)
        at com.mud.utils.Printer.inlargeStringFormatWidthByColourSymbols(Printer.java:63)
        at com.mud.utils.Printer.formatMessage(Printer.java:36)
        at com.mud.utils.Printer.printToChar(Printer.java:42)
        at com.mud.functions.do_fun.wiz_skills.DoMstat.execute(DoMstat.java:106)
        at com.mud.core.interp.InterpC.do_function(InterpC.java:88)
        at com.mud.functions.do_fun.wiz_skills.DoStat.execute(DoStat.java:136)
        at com.mud.core.interp.InterpC.interpret(InterpC.java:298)
        at com.mud.core.interp.InterpC.substitute_alias(InterpC.java:441)
        at com.mud.server.GameThread.processInput(GameThread.java:120)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)

2017-06-06 22:42:05,174  INFO com.mud.core.actionWiznet.ActWizC - Zaero:L:quit
2017-06-06 22:42:05,176  INFO com.mud.core.actionWiznet.ActWizC - Zaero <EF><EE><EA><E8><ED><F3><EB>(<E0>) <E8><E3><F0><F3>.
2017-06-06 22:42:05,177  INFO com.mud.model.descriptor.DescriptorData - Closing link to Zaero
2017-06-06 22:42:05,178  INFO com.mud.model.descriptor.DescriptorData - Zaero<<C2><F1><E5> <F5><EE><F0><EE><F8><E5><E5> <F0><E0><ED><EE> <E8><EB><E8> <EF><EE><E7><E4><ED><EE> <E7><E0><EA><E0><ED><F7><E8><E2><E0><E5><F2><F1><FF>.
^MESC[0m
2017-06-06 22:42:05,179  INFO com.mud.model.descriptor.DescriptorData - Closing link to <DB><E5><F8><F2><EF><F3><EA>
2017-06-06 22:42:05,179 ERROR com.mud.model.merc_h.MercH - Char is nowhere: 0
java.lang.RuntimeException: Char is nowhere: 0
        at com.mud.model.merc_h.MercH.bug(MercH.java:131)
        at com.mud.core.skills.BattleSkills.stop_fighting(BattleSkills.java:652)
        at com.mud.core.handler.Obj.extract_char(Obj.java:428)
        at com.mud.model.descriptor.DescriptorData.removeCharFromTheWorld(DescriptorData.java:140)
        at com.mud.model.descriptor.DescriptorData.disconnectChar(DescriptorData.java:121)
        at com.mud.functions.do_fun.DoQuit.execute(DoQuit.java:155)
        at com.mud.core.interp.InterpC.interpret(InterpC.java:298)
        at com.mud.core.interp.InterpC.substitute_alias(InterpC.java:431)
        at com.mud.server.GameThread.processInput(GameThread.java:120)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)
2017-06-06 22:42:05,180 ERROR com.mud.model.merc_h.MercH - Char is nowhere: 0
java.lang.RuntimeException: Char is nowhere: 0
        at com.mud.model.merc_h.MercH.bug(MercH.java:131)
        at com.mud.core.skills.BattleSkills.stop_fighting(BattleSkills.java:652)
        at com.mud.core.handler.Obj.extract_char(Obj.java:428)
        at com.mud.functions.do_fun.DoQuit.execute(DoQuit.java:156)
        at com.mud.core.interp.InterpC.interpret(InterpC.java:298)
        at com.mud.core.interp.InterpC.substitute_alias(InterpC.java:431)
        at com.mud.server.GameThread.processInput(GameThread.java:120)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)

**Comment by annadrogalchuk** [comment]
куча разных багов. Часть уже исправлены, а с брокен пайп я не знаю, что делать пока
