### ISSUE TITLE
Lang ua

### ISSUE THREAD

**Issue by Stinger83** [Drogalchuk/Mud#21]
Stinger:W:lang ua
2017-06-11 19:38:19,523  INFO com.mud.core.actionWiznet.ActWizC - Stinger:W:lang ua
2017-06-11 19:38:19,524  INFO com.mud.model.descriptor.DescriptorData - Stinger<лНБС ГЛЁМЕМН

[пШМНВМЮЪ_оКНЫЮДЭ_мНБНЦН_рЮКНЯЮ] q7656p пЮМНЙ none
34655/34655hp 34435/34435m 2526/6305mv 4053.486 NESW -984 *0* +0 3000xp

2017-06-11 19:38:21,081  INFO com.mud.model.descriptor.TelnetDescriptorData - Stinger>ll

2017-06-11 19:38:21,083  INFO com.mud.model.descriptor.DescriptorData - Stinger<ьН?
[пШМНВМЮЪ_оКНЫЮДЭ_мНБНЦН_рЮКНЯЮ] q7656p пЮМНЙ none
34655/34655hp 34435/34435m 2526/6305mv 4053.486 NESW -984 *0* +0 3000xp

2017-06-11 19:38:22,831  INFO com.mud.model.descriptor.TelnetDescriptorData - Stinger>sc

Stinger:W:sc
2017-06-11 19:38:22,831  INFO com.mud.core.actionWiznet.ActWizC - Stinger:W:sc
2017-06-11 19:38:22,833  INFO com.mud.model.descriptor.DescriptorData - Stinger<$i2 рСР.
                Stinger
мЮ north:
                цНПД
                РСГЕЛМШИ
мЮ east :
                РЕКНУПЮМХРЕКЭ
                РСПХЯР
мЮ south:
                йНПНКЕБЯЙХИ
                пЕИЯРКХМ
мЮ west :
                РЕКНУПЮМХРЕКЭ
                РЕКНУПЮМХРЕКЭ
                РСГЕЛМШИ
                ЯАНПЫХЙ

[пШМНВМЮЪ_оКНЫЮДЭ_мНБНЦН_рЮКНЯЮ] q7656p пЮМНЙ none
34655/34655hp 34435/34435m 2539/6305mv 4053.486 NESW -984 *0* +0 3000xp

2017-06-11 19:38:25,082  INFO com.mud.model.descriptor.TelnetDescriptorData - Stinger>l

Stinger:W:look
2017-06-11 19:38:25,082  INFO com.mud.core.actionWiznet.ActWizC - Stinger:W:look
2017-06-11 19:38:25,084 ERROR com.mud.server.GameThread - java.util.MissingFormatArgumentException: Format specifier '%s'
java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at com.mud.utils.Printer.formatMessage(Printer.java:38)
        at com.mud.utils.Printer.printToChar(Printer.java:42)
        at com.mud.core.actionInfo.ShowListToChar.show_list_to_char(ShowListToChar.java:57)
        at com.mud.functions.do_fun.DoLook.execute(DoLook.java:99)
        at com.mud.core.interp.InterpC.interpret(InterpC.java:298)
        at com.mud.core.interp.InterpC.substitute_alias(InterpC.java:441)
        at com.mud.server.GameThread.processInput(GameThread.java:120)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)
java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at com.mud.utils.Printer.formatMessage(Printer.java:38)
        at com.mud.utils.Printer.printToChar(Printer.java:42)
        at com.mud.core.actionInfo.ShowListToChar.show_list_to_char(ShowListToChar.java:57)
        at com.mud.functions.do_fun.DoLook.execute(DoLook.java:99)
        at com.mud.core.interp.InterpC.interpret(InterpC.java:298)
        at com.mud.core.interp.InterpC.substitute_alias(InterpC.java:441)
        at com.mud.server.GameThread.processInput(GameThread.java:120)
        at com.mud.server.GameThread.run(GameThread.java:40)
        at java.lang.Thread.run(Thread.java:748)
2017-06-11 19:38:25,094  INFO com.mud.model.descriptor.DescriptorData - Stinger<пШМНВМЮЪ_оКНЫЮДЭ_мНБНЦН_рЮКНЯЮ
  щРН_ЯЮЛЮЪ_АНКЭЬЮЪ_ОКНЫЮДЭ_мНБНЦН_рЮКНЯЮ._оНОЮБ_ЯЧДЮ,1A H T U N G !!!: Format specifier '%s'

**Comment by annadrogalchuk** [comment]
нужно смотреть локализационные файлы этой арии
